port: 8083
access_token_expiration_seconds: 900
refresh_token_expiration_seconds: 86400

# Specific CORS configuration
allowed_origins: "http://localhost:3000,http://example.com"

oauth2:
  enabled: true

login_api:
  enabled: true

users:
  - id: "1"
    username: "user1"
    password: "password1"
    attributes:
      email: "user1@example.com"

clients:
  - id: "client1"
    audience: "example.com"
    secret: "super_secret"
    redirect_uri: "http://localhost:3000/callback"
