services:
  idp:
    build:
      context: ../../../
      dockerfile: Dockerfile
    volumes:
      - ./local-idp.config.yaml:/config.yaml:ro
    ports:
      - "8085:8085"
    environment:
      - PORT=8085
