port: 8085

# Very short token expiration for testing
access_token_expiration_seconds: 1    # 1 second
refresh_token_expiration_seconds: 2   # 2 seconds

allowed_origins: "*"

oauth2:
  enabled: true

login_api:
  enabled: true

users:
  - id: "1"
    username: "user1"
    password: "password1"
    attributes:
      email: "user1@example.com"

clients:
  - id: "client1"
    audience: "example.com"
    secret: "super_secret"
    redirect_uri: "http://localhost:3000/callback"
